theme = "system"  # system, light, dark

[widgets]
displayed = [
  "default.spaces",
  "spacer",
  { "default.time" = { time-zone = "America/Guatemala", format = "H:mm 'HN'" } },
  { "default.time" = { time-zone = "America/Panama", format = "H:mm 'PA'" } },
  { "default.time" = { time-zone = "GMT", format = "H:mm zzz" } },
  "default.battery",
  "default.time",

  # What I would actually like is:
  # [
  #   { "default.time" = { time-zone = "America/Guatemala", format = "H:mm 'HN'" } },
  #   { "default.time" = { time-zone = "America/Panama", format = "H:mm 'PA'" } },
  #   { "default.time" = { time-zone = "GMT", format = "H:mm zzz" } },
  # ],
  # [
  #   "default.battery",
  #   "default.time",
  # ]
]

[widgets.default.spaces]
space.show-key = true  # show space number (or character, if you use AeroSpace)
window.show-title = true
window.title.max-length = 20

[widgets.default.battery]
show-percentage = false
warning-level = 30
critical-level = 10

[widgets.default.time]
format = "E, dd/MM HH:mm 'UY'"
calendar.format = "J:mm"
calendar.show-events = false
# calendar.allow-list = ["Home", "Personal"] # show only these calendars
# calendar.deny-list = ["Work", "Boss"] # show all calendars except these

[popup.default.time]
view-variant = "box"

[background]
enabled = false

[experimental.foreground]
height = 40
blur = 1
horizontal-padding = 5
spacing = 15

[experimental.foreground.widgets-background]
displayed = true
blur = 3

[experimental.background]
displayed = false
height = "menu-bar"
blur = 6
