on-focus-changed = [
  'exec-and-forget printf "refresh" > tmp/barik.fifo',
]
exec-on-workspace-change = [
  '/bin/zsh -c "printf refresh > tmp/barik.fifo',
]
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30
# Possible values: tiles|accordion
default-root-container-layout = "tiles"
# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = "auto"
# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ["move-mouse monitor-lazy-center"]
# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = false

[exec.env-vars]
REFRESH_WIDGET = '/bin/zsh -c "printf refresh > tmp/barik.fifo"'

[[on-window-detected]]
if.app-name-regex-substring = "Zen"
if.window-title-regex-substring = "Picture-in-Picture"
run = "layout floating"

# Possible values: (qwerty|dvorak|colemak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = "qwerty"

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See:
#                 https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 5
inner.vertical = 5
outer.left = 5
outer.bottom = 5
outer.top = 40
outer.right = 5

[mode.main.binding]
# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
#                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
#                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
#                   sectionSign (ISO keyboards only, european keyboards only)
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# You can uncomment the following lines to open up terminal with alt + enter shortcut
# (like in i3)
# alt-enter = '''exec-and-forget osascript -e '
# tell application "Terminal"
#     do script
#     activate
# end tell'
# '''

# Layouts
cmd-shift-r = "layout tiles accordion"
cmd-shift-f = "layout floating tiling"
# See: https://nikitabobko.github.io/AeroSpace/commands#focus
cmd-h = "focus left --boundaries-action wrap-around-the-workspace"
cmd-j = "focus down --boundaries-action wrap-around-the-workspace"
cmd-k = "focus up --boundaries-action wrap-around-the-workspace"
cmd-l = "focus right --boundaries-action wrap-around-the-workspace"
# See: https://nikitabobko.github.io/AeroSpace/commands#move
cmd-shift-h = [
  "move left",
  'exec-and-forget /bin/zsh -c "printf refresh > tmp/barik.fifo"'
]
cmd-shift-j = [
  "move down",
  'exec-and-forget /bin/zsh -c "printf refresh > tmp/barik.fifo"'
]
cmd-shift-k = [
  "move up",
  'exec-and-forget /bin/zsh -c "printf refresh > tmp/barik.fifo"'
]
cmd-shift-l = [
  "move right",
  'exec-and-forget /bin/zsh -c "printf refresh > tmp/barik.fifo"'
]
# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
cmd-1 = "workspace 01"
cmd-2 = "workspace 02"
cmd-3 = "workspace 03"
cmd-4 = "workspace 04"
cmd-5 = "workspace 05"
cmd-6 = "workspace 06"
cmd-7 = "workspace 07"
cmd-8 = "workspace 08"
cmd-9 = "workspace 09"
cmd-0 = "workspace 10"
cmd-ctrl-1 = "workspace 11"
cmd-ctrl-2 = "workspace 12"
cmd-ctrl-3 = "workspace 13"
cmd-ctrl-4 = "workspace 14"
cmd-ctrl-5 = "workspace 15"
cmd-ctrl-6 = "workspace 16"
cmd-ctrl-7 = "workspace 17"
cmd-ctrl-8 = "workspace 18"
cmd-ctrl-9 = "workspace 19"
cmd-ctrl-0 = "workspace 20"
# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
cmd-shift-1 = "move-node-to-workspace 01"
cmd-shift-2 = "move-node-to-workspace 02"
cmd-shift-3 = "move-node-to-workspace 03"
cmd-shift-4 = "move-node-to-workspace 04"
cmd-shift-5 = "move-node-to-workspace 05"
cmd-shift-6 = "move-node-to-workspace 06"
cmd-shift-7 = "move-node-to-workspace 07"
cmd-shift-8 = "move-node-to-workspace 08"
cmd-shift-9 = "move-node-to-workspace 09"
cmd-shift-0 = "move-node-to-workspace 10"
cmd-ctrl-shift-1 = "move-node-to-workspace 11"
cmd-ctrl-shift-2 = "move-node-to-workspace 12"
cmd-ctrl-shift-3 = "move-node-to-workspace 13"
cmd-ctrl-shift-4 = "move-node-to-workspace 14"
cmd-ctrl-shift-5 = "move-node-to-workspace 15"
cmd-ctrl-shift-6 = "move-node-to-workspace 16"
cmd-ctrl-shift-7 = "move-node-to-workspace 17"
cmd-ctrl-shift-8 = "move-node-to-workspace 18"
cmd-ctrl-shift-9 = "move-node-to-workspace 19"
cmd-ctrl-shift-0 = "move-node-to-workspace 20"
